[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Remappings for usage in script/others
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/",
    "poseidon-solidity/=lib/poseidon-solidity/contracts"
]

# Enable filesystem access for reading/writing files
fs_permissions = [
    { access = "read", path = "./data" },
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./out" },
    { access = "write", path = "./out" }
]