[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Remappings for usage in script/others
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/"
]

# Enable filesystem access for reading/writing files
fs_permissions = [
    { access = "read-write", path = "./" },
    { access = "read-write", path = "../" },
    { access = "read", path = "./data" },
    { access = "read", path = "./broadcast" },
    { access = "read-write", path = "./out" },
    { access = "read", path = "../out" },
]